### PR TITLE
Monorepo dev docker

### PR DESCRIPTION
**Pull request by crkrenn**
@patcon, branch monorepo-dev is currently exactly the same as monorepo. monorepo-dev-docker is almost exactly the same as your docker-dev branch with the exception of renaming the directories and updating the docker-compose.yml file. 

Can you either verify that the monorepo-dev-docker branch works or tweak it if possible so that it does?

If it does work, can you approve the pull request?

This would define monorepo-dev as our new working branch. 

Does this make sense?

Thanks!

### CODE REVIEW

**Comment by ballPointPenguin** [comment]
These changes look really good @crkrenn . I'm going to test this an a couple machines and see how it goes.

I'm curious about `SERVICE_URL: 'https://preprod.pol.is'`. Is this configuration meant to interact with that endpoint, rather than rerly on only local / docker containers?

**Comment by crkrenn** [comment]
The endpoint ‘https://preprod.pol.is' is just there because it was in one of the original code base’s config files. There is more “pol.is” hard coding that needs to be pulled out. Probably on a separate branch.

-Chris


--------------------------------------------
Q: Why is this email [hopefully] five sentences or less?
A: http://five.sentenc.es

**Comment by ballPointPenguin** [comment]
I had to change the directory names in docker-compose:
https://github.com/pol-is-trial-balloon/polis/pull/17/files

**Comment by ballPointPenguin** [comment]
removing all my docker containers, volumes, images and building this fresh (Mac OS if it matters). I just got to this:

```
Step 10/12 : ADD polis.config.template.js polis.config.js
 ---> 8e0af9bc25a4
Step 11/12 : ADD . .
 ---> 018d17ba7d6d
Step 12/12 : RUN gulp deployPreprod
 ---> Running in 09cb4c666752
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/app/node_modules/natives/index.js:137:5)
    at require (/app/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/app/node_modules/natives/index.js:137:5)
    at require (/app/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/app/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/app/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/app/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
ERROR: Service 'client' failed to build: The command '/bin/sh -c gulp deployPreprod' returned a non-zero code: 1
```

**Comment by patcon** [comment]
Hm. Never hit that one before...

Maybe you ran across this, but I read just now in a few issues that it seems to be related to compiling `natives` pkg (via `graceful-fs`) on diff versions of node. Fix in some cases was deleting `node_modules/` and starting over. Any chance your node_modules dir from a local install run was copied into the container during build's `ADD . .` step?

Ref: https://github.com/nodejs/node/issues/25132

I'll try to reproduce later :)

**Comment by patcon** [comment]
Was able to reproduce! Odd. Not sure what changed, but I'll try a bisect

**Comment by patcon** [comment]
Ah yeah, I see what happened. I recently I cherry-picked from the `package-log.json` @metasoarous had generated locally and added it to polisClientParticipation. (It says "12 days ago" in git logs, but I cherry-picked more recently, in case that's a point of confusion.)

Seems it was specific to env he generated it within

I'll delete and regenerate

**Comment by patcon** [comment]
Fixed in 629aade6 (Also, pushed some docker-compose namespace changes)

**Comment by patcon** [comment]
Ah shoot. I also rebased my patcon:docker-dev against monorepo before pushing these new commits, and didn't realize it would mess this up. I'll force push to this branch.

**Review by patcon — APPROVED** [review]
Just rebuilt from scratch and works

**Comment by patcon** [comment]
I'll start prefixing my feature branches with `feature/` to clarify the different types of branches we're now using.

If I'm understanding correctly, we're now creating all feature branches off `monorepo-dev`, and PRs will be created and merged only into that branch, instead of into `monorepo`? (at least until an upstream merge happens?)

**Comment by patcon** [comment]
Since it's the one getting updates now, could we set default branch in this repo to `monorepo-dev` rather than `monorepo`?

**Comment by crkrenn** [comment]
+1 on changing default branch to monorepo-dev

**Comment by metasoarous** [comment]
Can we merge these changes yet!?

**Comment by colinmegill** [comment]
Very exciting to see this come together :)

**Comment by crkrenn** [comment]
* monorepo-dev-docker ran for me on os x just fine.
* nginx-server is not automatically redirecting XXX.XXX.XXX.XXX:5000 to XXX.XXX.XXX.XXX:5000/home (on os x). 
* I thought the solution was in tweaking the [`file-server/nginx.site.default.conf`](https://github.com/pol-is-trial-balloon/polis/tree/monorepo-dev-docker/file-server) file
     * I unsuccessfully tried `try_files $uri $uri/ /home?q=$uri&$args;` from https://www.digitalocean.com/community/questions/nginx-fails-to-redirect-to-index-php
     * I unsuccessfully tried `rewrite ^/$ home permanent;` from https://www.liquidweb.com/kb/redirecting-urls-using-nginx/
     * I unsuccessfully tried `location = / {  try_files home;}`
* Should I be looking at tweaking `file-server/app.js` instead   ?
* @urakagi, do you have suggestions?

Below is the full current `file-server/nginx.site.default.conf` file
```
server {
    listen       80;
    server_name  localhost;

    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://server:5000;
    }
}
```

**Comment by crkrenn** [comment]
Update.. I think it was something to do with a cache in my chrome browser. Firefox and Safari redirected fine, as did Chrome incognito. 

Any objections to merging monorepo-dev-docker to monorepo-dev now?

@urakagi, sorry for the false alarm ;)

**Comment by metasoarous** [comment]
Once this is merged, I'll get it merged into `pol-is:dev` as well!

**Comment by patcon** [comment]
@crkrenn I submitted these commits in the merged https://github.com/pol-is/polisServer/pull/65, so I think this PR is superceded by that, yes? Sorry if i misunderstood -- i think i was a little confused by our branching strategy. I thought this PR was only active until @metapolis found time to make merges, so I submitted a PR for the `docker-dev` feature branch directly.

**Comment by patcon** [comment]
As I understand, now that we've merged both `pol-is-trial-balloon:monorepo` (https://github.com/pol-is/polisServer/pull/60) and `patcon:docker-dev` (https://github.com/pol-is/polisServer/pull/65) into `pol-is:dev`:
- this PR can be closed
- `pol-is-trial-balloon:monorepo-dev` can be deleted
- `pol-is-trial-balloon:monorepo-dev-docker` can be deleted

**Pull request closed without merging**
